name: setting up environment

on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         timeout-minutes: 100
         run: |
           sudo apt install expect -y
           sudo apt install python3
           git config --global user.name "rui-ports"
           git config --global user.email "secrets.EMAILGIT"
           mkdir hehehe &&cd hehehe
           git clone https://${{ secrets.EMAIL }}":${{ secrets.PASSWORD }}"@github.com/rui-ports/mirroring.git hehehe

       - name: Run
         continue-on-error: true
         timeout-minutes: 350
         run: |
           git clone https://${{ secrets.EMAIL }}":${{ secrets.PASSWORD }}"@github.com/rui-ports/mirroring.git mbot
           cd mbot
           sudo docker build . -t mirror-bot
           sudo docker run mirror-bot

       - name: test
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd hehehe/hehehe
              echo "1" >> push.txt
              git add .
              git commit -m "Loop workflow"
