name: setting up environment

on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         timeout-minutes: 100
         run: |
           sudo apt install expect -y
           sudo apt install python3
           git config --global user.name "rui-ports"
           git config --global user.email "secrets.EMAILGIT"
           mkdir hehehe &&cd hehehe
           git clone https://github.com/rui-ports/kang hehehe

       - name: Run
         continue-on-error: true
         timeout-minutes: 1
         run: |
           git clone https://${{ secrets.EMAIL }}":${{ secrets.PASSWORD }}"@github.com/rui-ports/mirroring.git mbot
           cd mbot
           sudo docker build . -t mirror-bot
           sudo docker run mirror-bot

       - name: test
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd hehehe/hehehe
              echo "1" >> push.txt
              git add .
              git commit -m "Loop workflow"


       - name: Reruns
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd hehehe/hehehe
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"qrovic\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
